Removed empty parentheses from '$dumpon' system task call, so that VCS doesn't complain
* Removed empty parentheses from '$dumpon' system task call, so that VCS doesn't throw the error:
  Error-[TMAFTC] Too many arguments to function/task call
  wave_dump.sv, 4
  "$dumpon();"
    The above function/task call is done with more arguments than needed.